# Basic configurations of RSSeg dataset

seed: 1024

datasets:
  train: !Node
    type: SegDataset
    args:
      data_dir: ./test_tipc/data/rsseg/
      file_list: ./test_tipc/data/rsseg/train.txt
      label_list: ./test_tipc/data/rsseg/labels.txt
      num_workers: 0
      shuffle: True
  eval: !Node
    type: SegDataset
    args:
      data_dir: ./test_tipc/data/rsseg/
      file_list: ./test_tipc/data/rsseg/val.txt
      label_list: ./test_tipc/data/rsseg/labels.txt
      num_workers: 0
      shuffle: False
transforms:
  train:
    - !Node
      type: DecodeImg
    - !Node
      type: Resize
      args:
        target_size: 512
    - !Node
      type: RandomHorizontalFlip
      args:
        prob: 0.5
    - !Node
      type: Normalize
      args:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
  eval:
    - !Node
      type: DecodeImg
    - !Node
      type: Resize
      args:
        target_size: 512
    - !Node
      type: Normalize
      args:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
    - !Node
      type: ReloadMask
download_on: False
download_url: https://paddlers.bj.bcebos.com/datasets/rsseg.zip
download_path: ./test_tipc/data/

num_epochs: 10
train_batch_size: 4
save_interval_epochs: 10
log_interval_steps: 4
save_dir: ./test_tipc/output/seg/
learning_rate: 0.001
early_stop: False
early_stop_patience: 5
use_vdl: False
resume_checkpoint: ''