# Configurations of DeepLab V3+ with RSSeg dataset

_base_: ../_base_/rsseg.yaml

save_dir: ./test_tipc/output/seg/deeplabv3p/

model: !Node
  type: DeepLabV3P
  args:
    in_channels: 3
    num_classes: 5