# Basic configurations of UNet

_base_: ../_base_/rsseg.yaml

save_dir: ./test_tipc/output/seg/unet/

model: !Node
    type: UNet
        args:
            input_channel: 10
            num_classes: 5